- name: "dependencies"
  color: "0366d6"
  description: "Dependency updates"
- name: "ci"
  color: "1d76db"
  description: "CI and workflow changes"
- name: "rust"
  color: "dea584"
  description: "Rust-related changes"
- name: "docker"
  color: "0db7ed"
  description: "Docker-related changes"
